GET http://localhost:8080/getMoreBooks/2

###
POST http://localhost:8080/render/bookDisplay
Content-Type: application/json

{
  "books": [
    {
      "id": 13,
      "title": "Mr.",
      "author": "qzl2CfqtaY",
      "isbn": "6dLUINbB5r",
      "format": "HY2UtVvKCK",
      "filePath": "C:\\Users\\Administrator\\Pictures\\img_468676.png",
      "uploadedBy": "MOcHIDmqle",
      "status": "7ctcjvscRY",
      "cover": "static/images/cover/00001.jpg",
      "categoryId": 0,
      "fileSize": 420.09,
      "averageRating": 0.0,
      "reviewsCount": 0,
      "ratingCount": 0,
      "shelfCount": 0
    },
    {
      "id": 14,
      "title": "Miss.",
      "author": "FDmLST8tQc",
      "isbn": "lSeN9cPgfY",
      "format": "23qtGNXR89",
      "filePath": "C:\\Users\\Administrator\\Pictures\\img_987995.jpg",
      "uploadedBy": "NLzyVpZCEd",
      "status": "Ur6cKWbfAy",
      "cover": "static/images/cover/00001.jpg",
      "categoryId": 0,
      "fileSize": 186.54,
      "averageRating": 0.0,
      "reviewsCount": 0,
      "ratingCount": 0,
      "shelfCount": 0
    },
    {
      "id": 15,
      "title": "Mrs.",
      "author": "8dlcdMEDrh",
      "isbn": "QNEWXecHlp",
      "format": "XGtUpwe8JY",
      "filePath": "/Users/Administrator/Pictures/img_128136.png",
      "uploadedBy": "rlJyxvTcW0",
      "status": "VJnAASIuIv",
      "cover": "static/images/cover/00001.jpg",
      "categoryId": 0,
      "fileSize": 24.65,
      "averageRating": 0.0,
      "reviewsCount": 0,
      "ratingCount": 0,
      "shelfCount": 0
    },
    {
      "id": 16,
      "title": "Mr.",
      "author": "oal70ySY6t",
      "isbn": "8LkaxVbQZJ",
      "format": "nAtpQuWBUY",
      "filePath": "C:\\Users\\Administrator\\Pictures\\img_062986.png",
      "uploadedBy": "rM2SphFUGP",
      "status": "K8snE084pO",
      "cover": "static/images/cover/00001.jpg",
      "categoryId": 0,
      "fileSize": 856.86,
      "averageRating": 0.0,
      "reviewsCount": 0,
      "ratingCount": 0,
      "shelfCount": 0
    },
    {
      "id": 17,
      "title": "Mr.",
      "author": "TkPJczGjaW",
      "isbn": "n6LdZ1GZss",
      "format": "I9v8n5kx68",
      "filePath": "/Users/Administrator/Pictures/img_008672.png",
      "uploadedBy": "ZRbmBzxLJc",
      "status": "5N7fOSvCSI",
      "cover": "static/images/cover/00001.jpg",
      "categoryId": 0,
      "fileSize": 560.39,
      "averageRating": 0.0,
      "reviewsCount": 0,
      "ratingCount": 0,
      "shelfCount": 0
    },
    {
      "id": 18,
      "title": "Miss.",
      "author": "LvaYTzA6sf",
      "isbn": "JgeHLGRnu3",
      "format": "Q1xLsjEtop",
      "filePath": "C:\\Users\\Administrator\\Pictures\\img_490476.png",
      "uploadedBy": "6CSMB48UCq",
      "status": "CreKAnQ21x",
      "cover": "static/images/cover/00001.jpg",
      "categoryId": 0,
      "fileSize": 159.29,
      "averageRating": 0.0,
      "reviewsCount": 0,
      "ratingCount": 0,
      "shelfCount": 0
    },
    {
      "id": 19,
      "title": "Mrs.",
      "author": "IePcNjTvSh",
      "isbn": "L6N0InxJxj",
      "format": "drBFg6q2K2",
      "filePath": "/home/Administrator/Pictures/img_919467.png",
      "uploadedBy": "3UUtcpEzLg",
      "status": "qAiv5Qib58",
      "cover": "static/images/cover/00001.jpg",
      "categoryId": 0,
      "fileSize": 562.98,
      "averageRating": 0.0,
      "reviewsCount": 0,
      "ratingCount": 0,
      "shelfCount": 0
    },
    {
      "id": 20,
      "title": "Prof.",
      "author": "NKsl1PHTMc",
      "isbn": "AwtczejWEQ",
      "format": "WmxKMhWr2I",
      "filePath": "/home/Administrator/Pictures/img_536816.png",
      "uploadedBy": "PXfLRqydSr",
      "status": "GoRtQptipz",
      "cover": "static/images/cover/00001.jpg",
      "categoryId": 0,
      "fileSize": 21.03,
      "averageRating": 0.0,
      "reviewsCount": 0,
      "ratingCount": 0,
      "shelfCount": 0
    },
    {
      "id": 21,
      "title": "Miss.",
      "author": "9067VjeKq3",
      "isbn": "iVtDaFpKCi",
      "format": "UT5vzOfodJ",
      "filePath": "/Users/Administrator/Pictures/img_758588.jpg",
      "uploadedBy": "yhKNXH5eQx",
      "status": "BN24uGTEhS",
      "cover": "static/images/cover/00001.jpg",
      "categoryId": 0,
      "fileSize": 52.4,
      "averageRating": 0.0,
      "reviewsCount": 0,
      "ratingCount": 0,
      "shelfCount": 0
    },
    {
      "id": 22,
      "title": "Mr.",
      "author": "ipfY6Pf0tW",
      "isbn": "bQ55nYxLzp",
      "format": "N52i7ElIBM",
      "filePath": "/home/Administrator/Pictures/img_474836.jpg",
      "uploadedBy": "Vg2oeDecRE",
      "status": "ViRAXJe4K6",
      "cover": "static/images/cover/00001.jpg",
      "categoryId": 0,
      "fileSize": 477.53,
      "averageRating": 0.0,
      "reviewsCount": 0,
      "ratingCount": 0,
      "shelfCount": 0
    },
    {
      "id": 23,
      "title": "Miss.",
      "author": "StZnVFz7Dz",
      "isbn": "S4BQ2231Yp",
      "format": "9yxoDetYNQ",
      "filePath": "/home/Administrator/Pictures/img_362686.png",
      "uploadedBy": "JcFY42cMDP",
      "status": "Re0ogq0ysD",
      "cover": "static/images/cover/00001.jpg",
      "categoryId": 0,
      "fileSize": 433.87,
      "averageRating": 0.0,
      "reviewsCount": 0,
      "ratingCount": 0,
      "shelfCount": 0
    },
    {
      "id": 24,
      "title": "Miss.",
      "author": "zEHnN5OYiY",
      "isbn": "wd5gWVu4tq",
      "format": "BaUlAE8FX4",
      "filePath": "/home/Administrator/Pictures/img_216159.png",
      "uploadedBy": "wV12NoXmn9",
      "status": "6yq0uhRHOZ",
      "cover": "static/images/cover/00001.jpg",
      "categoryId": 0,
      "fileSize": 825.58,
      "averageRating": 0.0,
      "reviewsCount": 0,
      "ratingCount": 0,
      "shelfCount": 0
    }
  ],
  "page": 2,
  "message": "success"
}


